### ISSUE TITLE
Support for Service Instance Sharing capability in PCF 2.2

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#113]
The SI Sharing capability is in PCF 2.1 as beta and will become GA in PCF 2.2 without any changes. We currently support this on PCF 2.1 using the commands that are described in their docs:

https://docs.cloudfoundry.org/devguide/services/sharing-instances.html

This could be used for any SCS service instance. Also, this already works on PWS although probably not as useful since it is a multitenant environment. We should still deploy this doc update to PWS docs.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/common/service-instance-sharing.html.

The only change I made was to the note at the beginning: we now state that SI sharing requires PCF 2.1 or later (we used to say that to use it with SCS, you had to sign in to PWS). I did check the CF docs on the commands and ours seem up to date.
