### ISSUE TITLE
Update actuator endpoints for Boot 2.0 changes

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#118]
See: http://docs.pivotal.io/spring-cloud-services/1-5/service-broker-and-instances.html#access-actuator-endpoints where now most of the endpoints are prefixed with `/actuator` as described at https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints.

**Comment by fifthposition** [comment]
Updated on all pages where we mention Actuator (can use browser search for "actuator"):

* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/security-overview.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/service-broker-and-instances.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/config-server/writing-client-applications.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/config-server/connectors.html
