### ISSUE TITLE
Update Client Dependencies for SCS 2.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#121]
Connectors will be 2.0, Finchley.RELEASE, and Boot 2.x most recent.

**Comment by fifthposition** [comment]
This is up at http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html.

The versions I used are:

* Spring Boot: 2.0.2
* Spring Cloud: Finchley.RELEASE
* Spring Cloud Services: 2.0.0.RELEASE
* Spring Gradle Dependency Management Plugin: 1.0.5.RELEASE

**Comment by csterwa** [comment]
@royclarkson could you take a look to make sure that the version numbers are correct above. Another set of eyes on it.

**Comment by royclarkson** [comment]
Yes, these are the current versions. Confirmed. 👍 However, I expect that Finchley.RELEASE will be based on Spring Boot 2.0.3.RELEASE, as it is currently scheduled to be released a few days prior. I'll add stories for this in starters/connectors projects.

**Comment by fifthposition** [comment]
Reopening to restore the info on 1.x tile / starter & connector versions.
