### ISSUE TITLE
Update version support for SCS 2.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#122]
Add new ordinal number to list on http://docs.pivotal.io/spring-cloud-services/1-5/common/index.html.

**Comment by fifthposition** [comment]
Blocked on determining the version number.

**Comment by csterwa** [comment]
@fifthposition the ordinal version number is `20` for SCS 2.0.x.

**Comment by fifthposition** [comment]
This is up at http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/ (scroll to "Services" heading).
