### ISSUE TITLE
Remove Open-Source pages for now

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#123]
Move them to a branch for now.

**Comment by fifthposition** [comment]
See the nav at:

* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/config-server/managing-service-instances.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/service-registry/managing-service-instances.html

404s at:

* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/config-server/oss.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/service-registry/oss.html
