### ISSUE TITLE
Add CLI endpoints to Security Overview

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#147]
From @scottfrederick:

"under http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/security-overview.html#spring-cloud-broker /  `Entry Points` we list all the `/dashboard` endpoints. there’s another set of `/cli` endpoints that are used by the SCS cf CLI plugins. don’t know if we care to add those or not."

These were added incrementally since SCS 1.4+.

**Comment by fifthposition** [comment]
@georgeharley Could you perhaps shed some light on what's worth covering here?

**Comment by georgeharley** [comment]
Hi @fifthposition, a couple more endpoints were added to the service broker in September 2017 to support some new SCS cf CLI commands. The commands are:  
* cf spring-cloud-service-stop
* cf spring-cloud-service-start
* cf spring-cloud-service-restart
* cf spring-cloud-service-restage
* cf spring-cloud-service-view  

Docs information on these commands is available [at the usual place](https://github.com/pivotal-cf/spring-cloud-services-cli-plugin/blob/master/docs/cli.md).  
The service broker endpoints that were added are:  
* `/cli/instances/{instanceId}/command` which accepts PUT requests containing the service instance ID plus an identifier for the operation to be carried out on the service instance (stop, start, restart, restage)
* `/cli/instances/{instanceId}` which accepts GET requests containing the service instance ID. This returns a JSON object containing detailed information on the backing apps. The cf plugin extracts information from this JSON to render the `cf spring-cloud-service-view` output.   
  
All of the new endpoints require OAuth2 authentication with management permission on the target service instance.  

Is this the kind of information you are looking for? Please let me know if there's any other way I can help. And sorry for the late response.
