### ISSUE TITLE
Update screenshots for PCF 2.2 OM on SCS 2.0.x pages

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#149]
With PCF 2.2, there is a new look and feel. This is a lower priority change to update the screenshots on the docs.

**Comment by fifthposition** [comment]
Up at:

* http://docs-scs.cfapps.io/spring-cloud-services/2-0/installation.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/product-upgrades.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/smoke-tests.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/tile-configuration.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/service-broker.html
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/service-instances.html

I only updated either Ops Manager screenshots (changed look and feel in 2.2) or outdated Apps Manager screenshots (changed look and feel at some point--maybe 2.0 or 2.1--and we had some left that were made on an earlier version). I also corrected some small errors in the docs and took out the bit about getting broker credentials via the SCS tile in Ops Manager (just omitted the text and screenshot).
