### ISSUE TITLE
Mention that generated certificate must be added to GCP load balancer config

### ISSUE THREAD

**Issue by odedia** [pivotal-cf/docs-spring-cloud-services#162]
I had to figure this out by trial and error, after generating the certificate in PAS tile, I had to copy and paste the public and private key to the GCP Load Balancer so that it will expose the self-signed certificate over to Spring Cloud Services apps. without doing this, it kept failing on SSL Handshake.

**Comment by csterwa** [comment]
Could we add this to our troubleshooting and ensure that we point to the PAS documentation when it is available?

**Comment by fifthposition** [comment]
PCF Docs story: https://www.pivotaltracker.com/n/projects/923920/stories/160329199

**Comment by mlimonczenko** [comment]
@odedia Which certificate in the PAS tile did you have to add to the GCP Load Balancer?
Specifically, the field in PAS.

**Comment by ljarzynski** [comment]
As far as PCF docs are concerned, we added a note to the certificate config field in PAS saying that you need to put this on your lb as well. commit here: https://github.com/pivotal-cf/docs-pcf-install/commit/a74e64d033c073ed4053acba884b6045e01f4b22. committed to all versions. 

@fifthposition Unless you feel like you should put a callout in the SCS docs, we can probably close this now
