### ISSUE TITLE
MySQL default service and plan are not clear

### ISSUE THREAD

**Issue by scottfrederick** [pivotal-cf/docs-spring-cloud-services#171]
The SCS tile configuration docs don't clearly state what the default MySQL service plan is. 

The [Tile Configuration](https://docs.pivotal.io/spring-cloud-services/2-0/tile-configuration.html#configure-service-broker-dependent-services) page contains this text: 

> By default, the Spring Cloud Services service broker uses the MySQL for PCF product’s 100mb service plan for a MySQL database...

This implies the MySQL v1 product (and the`p-mysql` service name), but only if the reader is familiar with the default plan names for the MySQL v1 and v2 products. 

The following screenshots show the MySQL service name and plan as `p.mysql` and `db-small`, which are not the default values. 

https://docs.pivotal.io/spring-cloud-services/2-0/installation.html
https://docs.pivotal.io/spring-cloud-services/2-0/tile-configuration.html#tile-configuration-options

see https://pivotal.slack.com/archives/C0DRHC7DW/p1534797930000100

**Comment by csterwa** [comment]
This is now `p.mysql` and `db-small` as defaults. It must be modified if these are not available.

**Comment by csterwa** [comment]
This is where it needs to be modified: https://docs.pivotal.io/spring-cloud-services/2-0/tile-configuration.html#configure-service-broker-dependent-services to v2.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/tile-configuration.html#configure-service-broker-dependent-services (screenshot shows v2 values, text doesn't say v1 _or_ v2 any more).
