### ISSUE TITLE
MySQL v2 migration suggested updates

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#175]
From Severine Tymon:

1) I would retitle the topic heading to "Migrating Data from MySQL for PCF v1 to v2" to reinforce the idea that it's DATA that's getting migrated. Also make the subnav link text and the topic heading match.
>
> 2) Small style nit, but we typically put "v" in front of version numbers-- so it should be Spring Cloud Services v2.0. This might not be a convention that you follow elsewhere in the doc, but just FYI.
>
> 3) Is this migration not possible to do with SCS v1.4 and earlier? The dropdown for this page pulls up a 404 for 1.4 and earlier. If that's the case, I would add a topic that explicitly states this just in case.
>
> 4) The migration for SCS sounds really easy peasy! Going through it though I think my only question is if SCS has any specific requirements or recommendations on what size plan to select? See this section https://docs.pivotal.io/p-mysql/2-3/migrate-to-v2.html#migrate-data
>
> 5) Do you want to provide any warnings on downtime or app availability during this time? I am not sure how typically large or small SCS datasets are.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/migrating-from-mysql-v1.html.
