### ISSUE TITLE
Update support FAQ

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-services#180]

**Comment by csterwa** [comment]
@fifthposition why is this blocked and is there more detail about what this entails?

**Comment by fifthposition** [comment]
I don't know why we have this issue honestly. I must have seen something out of date in it or something came up.

I wonder whether the support FAQ is used any more. It was mostly assembled some time ago and I wonder whether much of it helps with current SCS releases (now that 1.4 and previous versions are EOS). What do you think @csterwa? This issue may be worth closing.

**Comment by csterwa** [comment]
Agreed.
