### ISSUE TITLE
Add update to tile configuration for MySQL v1->v2 migration

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#182]
On the page at:

https://docs.pivotal.io/spring-cloud-services/1-5/migrating-from-mysql-v1.html

We should add an additional step at the end to update the tile configuration for the service broker to update with MySQL v2 values for the plan used when migrating.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/migrating-from-mysql-v1.html (see Step 4).
