### ISSUE TITLE
Add `refreshRate` property for `git` configuration on Config Server

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#183]
In 2.0.1 we released the ability to add `refreshRate` into the `git` configuration per repo.

https://github.com/pivotal-cf/spring-cloud-service-broker/commit/03e5819eac1e67e66a86b1918782ba5d001c60f8

We need to add this property into our Git configuration documentation and our release notes for 2.0.1. An example of how this is used:

```
$ cf create-service p-config-server standard config-server -c '{ "git":{ "uri": "https://github.com/spring-cloud-services-samples/cook-config", "label": "master", "pattern": "co*/dev*", "refreshRate": 200 } }'
```

`refreshRate` must be an Integer representing the number of seconds between refreshes.

**Comment by fifthposition** [comment]
This is up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/configuring-with-git.html#general-configuration
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/configuring-with-git.html#multiple-repositories
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html#2-0-1

**Comment by fifthposition** [comment]
Sigh... no, I didn't. I will restart this issue since I don't like to document something I haven't tested.

**Comment by csterwa** [comment]
@fifthposition did you already make the update? I saw this was still closed.

**Comment by fifthposition** [comment]
I did make the update and tested the example commands (they’re accepted and work to create or update SIs; I didn’t test the effect of the setting itself).

**Comment by ALMWEARE** [comment]
Is there a way we can disable the config server automatically getting refreshed during git push notification, as we want to refresh the config server only on demand for git changes.

**Comment by csterwa** [comment]
@ALMWEARE we are working on putting in more control of the Config Server updates in the upcoming SCS 3.0. Please stay tuned.
