### ISSUE TITLE
Broken links: Previous doc versions link to deleted or renamed files

### ISSUE THREAD

**Issue by sturzl** [pivotal-cf/docs-spring-cloud-services#184]
The documentation for PCF version 1.3, 1.5 etc. are available online. When clicking on links in those documents you are sent to the linked page but in the latest version of the docs. This causes broken links when documents are renamed or removed between versions.

**Case 1:** Scroll all the way to the bottom of this page and click on the "Updating an Instance link": [https://docs.pivotal.io/spring-cloud-services/1-3/common/config-server/creating-an-instance.html](https://docs.pivotal.io/spring-cloud-services/1-3/common/config-server/creating-an-instance.html)

**Case 2:**  At the top of the same page, change the version drop down from version 1.3 to version 2.0

**Comment by fifthposition** [comment]
Thanks for opening an issue @sturzl!

We will work on the issue you reported in Case 1. Unfortunately, as you found in Case 2, internal links can't always be relied upon to persist across documentation versions, especially across several as from 1.3 through 1.4 and 1.5 to 2.0. Sometimes in a new SCS minor or major release, we reorganize the documentation to make it more useful, and sometimes we add a page to documentation for a new version or remove a page if it's no longer needed. In the case here, we combined “Creating an Instance” and “Updating an Instance” from 1.3 so in 2.0, they're both sections in a page called "Managing Service Instances": https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/managing-service-instances.html. We can try to use redirects when possible to make this easier in the future though.

**Comment by sturzl** [comment]
Awesome, thanks for taking a look at this!

I agree a redirect would make a lot of sense for Case 2, when it comes up. Other defaults besides a 404 could also be helpful if specific redirect doesn't exist, or if maintaining redirects is more effort than it is worth. For example the drop down could link to some parent page in the docs, or links that would 404 could be disabled.

Thanks again!

**Comment by csterwa** [comment]
@sturzl this is no longer valid since we don't have 1.3.x docs to maintain on the production site anymore. Closing.
