### ISSUE TITLE
Encryption key documentation may be incorrect with SCS 2.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#188]
From Stephen Higgins in Slack at https://pivotal.slack.com/archives/C6EPQJJUV/p1539612308000100:

"Hi team, I have a question regarding creating a config server instance with the `encrypt` field. I followed the steps outline in the docs (https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/configuring-with-git.html#encryption-and-encrypted-values) , but I would continue to get a `create failed`. I was able to fix it by putting a `\n` at the end of each line of the RSA private key. However, the doc specifically provides steps to remove newlines with `openssl rsa -in server.key | tr -d '\n' > server_rsa.key`. Are the docs correct in recommending this? Thanks."

Based on what I see and loosely know, it seems like our docs may not be correct when used with SCS 2.0 that is based on Spring Boot 2. This my have changed after some support requests we've had recently in terms of `\n` in encryption key.

**Comment by fifthposition** [comment]
Updated to use awk (not tr) to escape (rather than strip) newline characters: http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/configuring-with-git.html#encryption-and-encrypted-values
