### ISSUE TITLE
Clarify HashiCorp Vault token configuration on bound application

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#193]
From @habuma:

"The document at https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/connectors.html#hashicorp-vault-token-renewal doesn’t make it clear (apparently) that `spring.cloud.config.token` is the same thing as `SPRING_CLOUD_CONFIG_TOKEN`. I’d be inclined to change it to something like…maybe: 

```
When the `SPRING_CLOUD_CONFIG_TOKEN` environment variable (or the `spring.cloud.config.token` property) is set on an app…
```

It would be good to clarify the way that the token is used from the client app and through Config Server instance to support backend call to HashiCorp Vault.

* The Vault token is specified with the `spring.cloud.config.token` configuration property, which may be set in any Spring Boot property source. It is recommended that it be set as an environment variable (as `SPRING_CLOUD_CONFIG_TOKEN`) so that it’s easy to update should the token expire.
* `SPRING_CLOUD_CONFIG_TOKEN` is sent to Config Server and then Config Server sends as `X-Vault-Token` header value to subsequent Vault API calls.

**Comment by fifthposition** [comment]
Clarified these sections:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/writing-client-applications.html#use-a-hashicorp-vault-server
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/connectors.html#hashicorp-vault-token-renewal
