### ISSUE TITLE
Clarify use RabbitMQ for PCF shared plan for `p-circuit-breaker-dashboard` service - backport to 1.5.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#194]
From Berti Jalon:

"[A customer] using SCS 2.0.2 had problems when creating a Circuit Breaker service instance because they thought that SCS uses _p.rabbitmq_ instead of _p-rabbitmq_ so they disabled service access of p-rabbitmq from org p-spring-cloud-services and enabled service access of p.rabbitmq from org p-spring-cloud-services . They say that the documentation is not clear which kind of service (multitenant VM or dedicated VM) and they thought that it would use p.rabbitmq since it’s newer technology.  I’ve seen it’s mentioned in this RabbitMQ for PCF doc https://docs.pivotal.io/rabbitmq-cf/1-14/replicator.html#scs-isolation (“SCS expects that the service is called p-rabbitmq”) that is linked from the Spring Cloud Services Doc https://docs.pivotal.io/spring-cloud-services/2-0/common/index.html#requirements in this text “Running SCS on a Dedicated RabbitMQ Cluster” but I couldn’t find any mention in SCS doc itself. I may just be missing it. I’m just sharing this with you, in case I’m not missing anything and you want to make some kind of mention in SCS doc to avoid confusion."

We should provide additional information about the RabbitMQ requirement along with mentioning as notes in docs anywhere that we have Circuit Breaker Dashboard use cases.

**Comment by fifthposition** [comment]
Updated references to RabbitMQ, most importantly "Requirements":

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/#requirements
