### ISSUE TITLE
SCS Connectors Vault support in 2.0.x needs @EnableScheduling

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#197]
We found out through long running support conversation with Jack at Vizient that automatic token renewal was not behaving as expected.

https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/connectors.html#hashicorp-vault-token-renewal

We should add the following code into the docs for writing client applications:

```
import org.springframework.scheduling.annotation.EnableScheduling
...
@EnableScheduling
...
```

I think this should also be referenced multiple times on the Connectors and Configuring with Vault pages.

**Comment by fifthposition** [comment]
@csterwa I don't think this is necessary on the "Configuring with Vault" page as that page is strictly about configuring the SI itself. I've added it to "Writing Client Applications" and mention it (don't describe how to do it) in "Spring Cloud Connectors" pages for Config Server:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/writing-client-applications.html#use-a-hashicorp-vault-server
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/connectors.html#hashicorp-vault-token-renewal

**Comment by fifthposition** [comment]
@csterwa I don't think this is necessary on the "Configuring with Vault" page, as that page is strictly about configuring the SI itself. I've added it to "Writing Client Applications" and mention it (don't describe how to do it) in "Spring Cloud Connectors" pages for Config Server:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/writing-client-applications.html#use-a-hashicorp-vault-server
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/config-server/connectors.html#hashicorp-vault-token-renewal
