### ISSUE TITLE
SCS Connectors 2.0.x uses Spring Boot 2.0.x only - not 2.1 compatible

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#199]
As Spring Boot 2.1 is releasing, we should add a note in our docs that mentions SCS Connectors 2.0.x with Finchley combination. We will be supporting Boot 2.1 when Greenwich comes out.

**Comment by fifthposition** [comment]
Added note above table:

http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html#including-dependencies

Also mentioned non-compatibility in that table entry for SCS starters 2.0.x.

**Comment by csterwa** [comment]
@fifthposition the only feedback I have is that the intro paragraph could be misleading:

`To work with Spring Cloud Services (SCS) service instances, your client app must include the following BOMs`

Probably should allow for clients setting up their own way to work with SCS instances. For instance, Steeltoe does this. We should allow for other languages to do the same. Maybe the following: 

`To work with Spring Cloud Services (SCS) service instances, your client app can include the following BOMs to automatically configure API access into your Spring Boot applications.`
