### ISSUE TITLE
SCS 2.0.3 & 2.0.4 release notes

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#200]
* Improved Azure service broker support for SCS service broker DB
* Increase errand VM size to support space needed for security scanning tools
* Upgraded Spring Security OAuth2 to greater than v2.3.4 to resolve CVE -> https://github.com/pivotal-cf/spring-cloud-service-broker/issues/598
* Fix dashboard redirect for instances < v2.0.0 due to change in actuator endpoints
* Fix issue with Vault token auto-renewal -> https://github.com/pivotal-cf/spring-cloud-services-connector/issues/80

The above are for both versions. The reason for two release is:
* 2.0.3 is based on 3468 stemcell version
* 2.0.4 is based on Xenial 97 stemcell version

**Comment by fifthposition** [comment]
Up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html#2-0-3
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html#2-0-4
