### ISSUE TITLE
SCS 1.5.9 release notes

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#201]
* Improved Azure service broker support for SCS service broker DB
* Increase errand VM size to support space needed for security scanning tools
* Fix issue with Vault token auto-renewal -> pivotal-cf/spring-cloud-services-connector#80

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/release-notes.html#1-5-9

I didn't include the last bullet, as it's a fix in connectors (not included in tile).
