### ISSUE TITLE
Pair down 3.0.x home page to only Config Server references

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#217]
* Remove all references to Service Registry and Circuit Breaker dashboard
* Remove all dependencies in Requirements section that don't pertain to SCS 3.0.x
* Current Config Server version will be ordinal number `30`
* Update Product Snapshot section for 3.0.x

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/index.html
