### ISSUE TITLE
Remove Security Overview for now on 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#218]
Until we have a full update of the Security Overview section we should remove it as to not confuse readers.

**Comment by fifthposition** [comment]
See:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/index.html (removed from nav)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/security-overview.html (404 -- topic removed for now)
