### ISSUE TITLE
Add Architecture Overview section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#219]
This can be based on Security Overview section although we should rewrite to separate architecture from security concerns:

https://docs.pivotal.io/spring-cloud-services/2-0/common/security-overview.html

Attached are some sequence diagrams that can be helpful along with high level architecture.

We should describe the following components and how they are deployed:

* SCS Service Broker and Mirror Service on BOSH deployed VM
* Config Server instance backing application in its own space within `p-spring-cloud-services` org on PAS
* Binding credentials in PAS CredHub and provided to client applications as reference
* Errand overviews

**Comment by csterwa** [comment]
![App API Calls to Config Server](https://user-images.githubusercontent.com/573621/57091755-bfdc9080-6cbe-11e9-8d0f-c0d377463360.png)
![Bind to Config Server service instance](https://user-images.githubusercontent.com/573621/57091756-bfdc9080-6cbe-11e9-869d-d81aa6fbcadc.png)
![Create Config Server Service Instance](https://user-images.githubusercontent.com/573621/57091758-bfdc9080-6cbe-11e9-9ac2-ad274495d858.png)
![Config Server for SCS 3 0 - High Level Architecture](https://user-images.githubusercontent.com/573621/57091781-cd921600-6cbe-11e9-8faf-9b5ec37f3dc6.png)

**Comment by fifthposition** [comment]
Do we still want this?

**Comment by csterwa** [comment]
No, not anymore. Thanks.
