### ISSUE TITLE
Update Operator Upgrades section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#222]
* Describe how you can run 2.0.x & prior versions alongside 3.0.x.
* Upgrade of Config Server is create new `p.config-server` instance, unbind previous instance, rebind new instance to app and then remove previous `p-config-server` instance when no apps are bound to it anymore.
* This will include a restart. If not scaled application then this could cause downtime.

**Comment by fifthposition** [comment]
Qs:

* How can an operator run 2.0.x or prior versions alongside 3.0.x--simply install 3.0.x on a PCF that already has earlier SCS versions, or is there anything else an operator needs to do?
* Can we elaborate on the potential for downtime during Config Server upgrades (including "If not scaled application then this could cause downtime")?

**Comment by csterwa** [comment]
@fifthposition yes, they install next to each other in OM. And no need for upgrade info at this time.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/product-upgrades.html
