### ISSUE TITLE
Remove Operator sections not needed in 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#223]
Remove sections:

* Troubleshooting
* Smoke tests
* Migrating from MySQL v1

**Comment by fifthposition** [comment]
Removed at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/

These all 404, just to be sure:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/migrating-from-mysql-v1.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/smoke-tests.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/product-troubleshooting.html
