### ISSUE TITLE
Update Operator Service Instances section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#226]
* Update service instance management
* Remove diagram
* Remove UAA Identity Zones section since it is no longer necessary
* Remove service instances dashboard section
* Point to Actuator Endpoints page instead of having section
* Update capacity requirements section

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/service-instances.html.

**Comment by csterwa** [comment]
I think that each instance is deployed with 2GB memory if I'm not mistaken. Can you check @fifthposition ?

**Comment by fifthposition** [comment]
I just checked a backing app (on the Djibouti environment) and it has 1G each for memory and disk.
