### ISSUE TITLE
Remove Developer Service Instance Upgrades section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#228]
Moved this information for `p.config-server` into Service Instances section already.

**Comment by fifthposition** [comment]
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/service-instance-upgrades.html (404)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/index.html (removed from nav)
