### ISSUE TITLE
Update Developer Client Dependencies section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#229]
* Remove references to Service Registry and Circuit Breaker Dashboard services
* Remove SCS tile versions prior to `1.5.x` in all tables
* Update client dependencies for SCS 3.0.x support

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/client-dependencies.html

cc @royclarkson @habuma for review

**Comment by csterwa** [comment]
Only a single change technically. SCS 2.0.x connectors are based on Boot 2.0 and is recommended to be used together. There were issues with using Boot 2.1 with SCS 2.0.x. I'd say we support 2.0.x & 2.1.x connectors with SCS tile 2.0.x. @fifthposition could you make the update for this?

**Comment by fifthposition** [comment]
@csterwa Done: http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/client-dependencies.html#including-dependencies
