### ISSUE TITLE
Remove Developer sections not applicable for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#230]
* Client Troubleshooting
* Service Instance Access
* Whole Service Registry navigation and sections
* Whole Circuit Breaker Dashboard navigation and sections

**Comment by fifthposition** [comment]
Up:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/ (removed from nav)

The following 404:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/client-troubleshooting.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/service-instance-access.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/service-registry/
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/circuit-breaker/
