### ISSUE TITLE
Update Config Server Overview section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#231]
Update diagram based on new architecture.

**Comment by csterwa** [comment]
I will create a new diagram that shows the updated architecture.

**Comment by csterwa** [comment]
![Config Server for SCS 3.0 - High Level Architecture.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54665871ed18e40200b525ad/125516c66e82c728ace21e0d46cb9b94258b84e9bcecad55a14fb092265467400a37e3783ed5a365ff6a7206074f32f9070d03548dbbda73fff26923ce1949b8c3714d3484624bf9ebc60db513bf72df1d83e5bc894a92ec6821e08b8f4d3b4b544a8af75527bc8b099906a214bc141ff1512469f477317646911b752a6b602ea9fbdd5e82972d.png)

@fifthposition What do you think of this diagram to replace the current one?

**Comment by fifthposition** [comment]
I think that works if we want to show the architecture more. We might want to explain the meaning of “R” though. It doesn’t show the user-facing aspect (fetch config and serve to client apps) though--is that OK?

**Comment by csterwa** [comment]
I will work on a diagram to provide the flow from user perspective. This will also help with acceptance test cases.

**Comment by csterwa** [comment]
Use the attached diagram in comment above. Also, change the context of the page to a section on how the Config Server works using diagram above and explanation of EnvironmentRepositories supported by SCS (Git, Vault, and CredHub). Describe the entire diagram flow.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/index.html
