### ISSUE TITLE
Update Configuring with Git section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#233]
* Ensure commands are updated for `p.config-server`
* Remove multiple Git repositories section since we don't support that now [backport to 2.0.x?]
* Remove section on encrypting values for Git: https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/configuring-with-git.html#encryption-and-encrypted-values

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/configuring-with-git.html
