### ISSUE TITLE
Update Composite Backends section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#235]
* Ensure commands are updated for `p.config-server`
* Note the use of `type` in the configuration objects of the array rather than `git` or `vault` naming convention due to OSS supported approach.

**Comment by fifthposition** [comment]
This is up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/composite-backends.html#general-configuration
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/composite-backends.html#proxy-servers (text unchanged--just the example command changed)
