### ISSUE TITLE
Remove Encrypted section from Configuration Properties for Config Server in 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#236]
Remove this section: https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/configuration-properties.html#encrypted-configuration

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/configuration-properties.html
