### ISSUE TITLE
Update Spring Cloud Connectors section for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#237]
* Update to show new configuration in client application's `cf env` output. Refer to what is in the CredHub reference.

**Comment by fifthposition** [comment]
Removed the "Service Detection" section and updated "Application Configuration". This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/connectors.html
