### ISSUE TITLE
Remove Config Server sections not applicable for 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#238]
Remove these sections:

* Using the dashboard
* Additional resources

**Comment by fifthposition** [comment]
This is up at

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/connectors.html (removed from nav)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/using-the-dashboard.html (404)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/config-server/resources.html (404)
