### ISSUE TITLE
Add Managing Secrets with CredHub section for Config Server in 3.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#239]
* How to add secrets to service instance
Example:
`curl -k https://config-server-$(cf service config-server --guid).[apps.domain]/secrets/application/default/master/key -H "Authorization: $(cf oauth-token)" -X PUT --data '{"key": "value"}' -H "Content-Type: application/json"`

  - `application` can be updated with application name that secret will be provided to
  - `key` can be changed to any key name

* How to remove secrets
Example:
`curl -k https://config-server-$(cf service config-server --guid).[apps.domain]/secrets/application/default/master/key -H "Authorization: $(cf oauth-token)" -X DELETE`

  - `application` must be application name that secret was added for
  - `key` is the key name to be deleted

**Comment by fifthposition** [comment]
Blocked for now as I'm not clear on our use of CredHub or what the developer workflow looks like. Will revisit as we get further on CH support.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html

**Comment by csterwa** [comment]
@fifthposition the only change I would make is to how the URL is located. I think we should change this in the section to use the new dashboard URL that we'll provide but I will put this into another story.
