### ISSUE TITLE
Remove all references to MySQL for PCF v1.x tile

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#241]
MySQL for PCF v1.x is no longer supported on PCF. We should remove any references, except v1 to v2 migration, and only support v2.x+.

**Comment by fifthposition** [comment]
Up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/#product-snapshot
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/#requirements

**Comment by csterwa** [comment]
@fifthposition we should also update versions of MySQL for PCF supported up to 2.5.x.

**Comment by fifthposition** [comment]
Updated.

* v2.0: http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/#product-snapshot
* v3.0: http://docs-pcf-staging.cfapps.io/spring-cloud-services/edge/common/#product-snapshot

**Comment by fifthposition** [comment]
In v2.0 of SCS, I've just removed other references to MySQL v1.

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/#product-snapshot (updated)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/installation.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/service-broker.html
