### ISSUE TITLE
Verify client dependencies for 3.0.0

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-services#243]
Double-check that what we have correct client dependencies for 3.0.0.

**Comment by csterwa** [comment]
Waiting for being closer to release.

**Comment by fifthposition** [comment]
Done. There's a 3.0.x branch on GitHub now for the Config Server sample app: https://github.com/spring-cloud-services-samples/cook/tree/3.0.x

We may want to do more cleanup there too (remove encryption example for one thing).
