### ISSUE TITLE
Add known issue about newlines on Git SSH keys between 1.5.x & 2.0.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#245]
From customer:

"I do think you could add some documentation about this breaking change between the 1.x and 2.x versions; upgrading a Config Service instance with an encryption key fails by default – you have to add the newline characters and then perform the upgrade for it to work."

We should add important notes into release notes and in the sections on Git SSH and Config Server encrypt configuration to update keys with newlines before upgrading service instances.

**Comment by csterwa** [comment]
Should go into troubleshooting section along with reference in release notes under migrating from 1.5.x.

**Comment by fifthposition** [comment]
@csterwa For release notes, I'm adding this as a top-level  (general 2.0.x) known issue (at the top). LMK if that works.

For the SSH key, that's not changed (unless I'm mistaken) in 2.0.x vs. 1.5.x. The requirement for escaped newlines (as `\n`) was already in 1.5.x for SSH keys and the documentation already covers it: https://docs.pivotal.io/spring-cloud-services/1-5/common/config-server/configuring-with-git.html#ssh-repository-access (see listing for `privateKey`). I don't think that the SSH key needing escaped newlines is a breaking change--the encryption key needing that _is_ a breaking change though.

**Comment by fifthposition** [comment]
This is up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html#known-issues (first known issue in the list)
* http://localhost:9292/spring-cloud-services/2-0/product-troubleshooting.html#1-5-config-server-using-encryption (linked to from known issue on "Release Notes")
