### ISSUE TITLE
Remove references to 1.4.x and prior versions

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#246]
On release notes for 2.0.x and 1.5.x docs, we still have reference 1.4.x and prior versions. We should remove all of these since these are now EOGS.

**Comment by fifthposition** [comment]
Removed from following pages

2.0:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/index.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html

1.5:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/release-notes.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/common/index.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/common/client-dependencies.html

**Comment by csterwa** [comment]
@fifthposition can you reverse the order of the client dependencies versions table so that 2.0 is on top rather than 1.5? This is on http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html

**Comment by fifthposition** [comment]
@csterwa I've reversed the order of all the version tables on that page for 2.0.x.
