### ISSUE TITLE
Update Client Dependencies to use SCS Starters 2.1.1.RELEASE

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#247]
Update client dependencies page to SCS Starters 2.1.1.RELEASE. And verify this works with our test applications. This should be updated in 3.0.x and 2.0.x doc versions.

**Comment by fifthposition** [comment]
This is up at 

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/client-dependencies.html (3.0.x)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html (2.0.x)
