### ISSUE TITLE
Remove mentions of CS encryption, SR, and CBD

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-services#249]
We currently still mention encryption features of Config Server in different places in the documentation (for example in "Writing Client Applications"). Remove these. Also remove any references to Service Registry and Circuit Breaker Dashboard.

**Comment by csterwa** [comment]
@fifthposition this is only for SCS 3.0, correct?

**Comment by fifthposition** [comment]
Yes. It sort of grew to include updating the operator pages, but it is only for SCS 3.0 (so we're removing SR and CBD mentions).

**Comment by fifthposition** [comment]
This is done. No mentions (that I'm aware of) of Config Server encryption, Service Registry, or Circuit Breaker Dashboard. See http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/
