### ISSUE TITLE
Update Client Dependencies to use SCS Starters 2.1.2.RELEASE

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#271]
See https://github.com/pivotal-cf/spring-cloud-services-connector/releases/tag/v2.1.2.RELEASE

**Comment by fifthposition** [comment]
This is up:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html (2.0.x)
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/client-dependencies.html (3.0.x)

@csterwa Please note that the *only* change I made was to the starters version for both 2.0.x and 3.0.x docs. If we need to update any other dependency versions, please let me know. cc @royclarkson
