### ISSUE TITLE
Add tile configuration step for MySQL v1 to v2 migration

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#293]
At https://docs.pivotal.io/spring-cloud-services/1-5/migrating-from-mysql-v1.html, it currently doesn't describe the need to update the SCS service broker tile configuration for MySQL service name and plan. It should reference updating the `Persistence store name and plan` section (step 5) at https://docs.pivotal.io/spring-cloud-services/2-0/installation.html to the new v2 plan being used in migration.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/1-5/migrating-from-mysql-v1.html
