### ISSUE TITLE
Update locating Config Server URL to use dashboard value

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#295]
At http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html#locating-service-instance-url

We should change this to use the `cf service [si name]` and use the `Dashboard` value instead. Some SpaceDeveloper permissioned users will not have access to `p-spring-cloud-services` org.

**Comment by fifthposition** [comment]
Great point and `cf service` approach is much simpler--thanks @csterwa!

Updated CredHub page and Actuator pages too:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html#locating-service-instance-url
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/actuator-endpoints.html#locating-service-instance-url
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/actuator-endpoints.html#locating-service-instance-url
