### ISSUE TITLE
Add section on running 3.0.x alongside previous version

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#299]
On Installation page, add section on running 3.0.x alongside previous versions (i.e. 2.0.x) and the reason this works. Include the following reasons:

* New name for `p.config-server` service in marketplace
* Still can use `p-service-registry` and `p-circuit-breaker-dashboard` services from 2.0.x
* Operators should think about disabling `p-config-server` in marketplace in lieu of new `p.config-server`
* There is no direct upgrade path except most `-c` JSON options will work in `p.config-server`. Therefore, recreating instances should work and rebinding to apps. (Removed `encrypt.key` and changed `composite` to use `type`)
* Backward compatible with SCS Connector 2.0.1.RELEASE (@fifthposition please verify versions)

Make the text more clear on `Upgrades` page to ensure there is no doubt that this is not going to affect earlier versions of SCS tile installations.

**Comment by fifthposition** [comment]
This is up for 3.0.x.

* "Installation" section: http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/installation.html#running-alongside-previous-versions
* "Upgrading" page: http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/product-upgrades.html
