### ISSUE TITLE
Ensure all tables have proper column widths for data

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#300]
* General Configuration section on Configuring with Git and Vault
* Proxy sections, as well

**Comment by fifthposition** [comment]
This is up at:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-service-instances.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-vault.html
