### ISSUE TITLE
Add note about not using SCS Connectors 1.6.1-1.6.3

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#301]
Versions 1.6.1-1.6.3 connectors should not be used due to problem with some configuration property values not being recognized properly. Please add note to Client Dependencies and SCS Connectors pages on 2.0.x, 3.0.x.

**Comment by fifthposition** [comment]
* 2.0.x: http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/client-dependencies.html#including-dependencies
* 3.0.x: http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/client-dependencies.html#including-dependencies
