### ISSUE TITLE
Configure Mirror Service persistent disk via Resource Config

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#302]
An Operator can configured the size of the persistent disk used to store Git mirrors using the `Resource Config` screen in the SCS tile configuration. The name of the row on that screen is `spring-cloud-services` and the `Persistent Disk Type` value is what can be configured. Operators should consider the disk space needed for mirroring all of their potential Config Server git repos plus some room for good measure. The default is currently set to 10GB.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/tile-configuration.html#mirror-service-resource-configuration.
