### ISSUE TITLE
Document backup & restore guidance for v3.1

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#307]
SCS 3.1 will come with backup and restore support. Items to discuss in the docs for backup & restore:

* Mirror Service persistent disk
* Mirror Service & SCS Broker MySQL DB
* Apps on PAS for backing the instances -> refer to PAS backup docs

Anything else?

**Comment by csterwa** [comment]
@spikymonkey I am adding this to the epic since it needs to be done in alignment with the implementation. Could you help by adding your backup/restore steps here so it can be documented?

**Comment by spikymonkey** [comment]
When the backup epic (#700) is complete, BBR will be able to backup and restore all of the state from the SCS Bosh VM. This includes both databases (`scs-service-broker` and `mirror-service` dbs) and the mirrored git repos. There's lots of good documentation on `bbr` itself [here](https://docs.cloudfoundry.org/bbr/)

Command to back up SCS state:

```
BOSH_CLIENT=<client id> \
BOSH_CLIENT_SECRET=<client secret> \
bbr deployment \
  --target <bosh director ip> \
  --deployment cf-spring-cloud-deployment \
  --ca-cert <bosh director ca cert> \
  backup
```

Command to restore SCS state:
```
BOSH_CLIENT=<client id> \
BOSH_CLIENT_SECRET=<client secret> \
bbr deployment \
  --target <bosh director ip> \
  --deployment cf-spring-cloud-deployment \
  --ca-cert <bosh director ca cert> \
  restore \
  --artifact-path <path/to/backup/directory>
```

The client id and client secret to use can be found from Ops Manager - they're called 'Bosh Command line credentials' in the credentials list for the Bosh director:

![Screenshot 2019-07-05 at 5 25 24 pm](https://user-images.githubusercontent.com/4227599/60735129-129a2900-9f4a-11e9-94fb-d622cff46264.png)

The IP address to use for the `--target` argument is the IP of the Bosh director, which can be found on the Bosh director Status tab:

![Screenshot 2019-07-05 at 5 27 33 pm](https://user-images.githubusercontent.com/4227599/60735167-33627e80-9f4a-11e9-9b86-777f5ac4380e.png)

Finally the bosh ca cert can be found on the Ops Man VM at `/var/tempest/workspaces/default/root_ca_certificate`, or you can grab it via the [ops manager api](https://docs.pivotal.io/pivotalcf/2-3/security/pcf-infrastructure/managing-certificates.html#root-certs)

**Comment by spikymonkey** [comment]
@fifthposition hope this helps explain what's coming :)

**Comment by fifthposition** [comment]
This is up on staging for 3.1: [Backing Up and Restoring Spring Cloud Services
](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/backup-and-restore.html)
