### ISSUE TITLE
Update backup & restore guidance to cover BBR

### ISSUE THREAD

**Issue by spikymonkey** [pivotal-cf/docs-spring-cloud-services#311]
SCS > 3.0 will use [Bosh Backup and Restore](https://docs.cloudfoundry.org/bbr/) to support backup/restore of the SCS Bosh VM, so we'll need to cover this in the docs.

**Comment by spikymonkey** [comment]
SCS 3.1.x will use [Bosh Backup and Restore](https://docs.cloudfoundry.org/bbr/) to support backup/restore of the SCS Bosh VM, so we'll need to cover this in the docs.

**Comment by csterwa** [comment]
Duplicate (although earlier) issue.
