### ISSUE TITLE
Request error: Get https://api.sys.domain/v2/info: dial tcp: i/o timeout

### ISSUE THREAD

**Issue by kumarganesh2814** [pivotal-cf/docs-spring-cloud-services#322]
Hi Team,

While installing SCS 1.5.6 we see errros as :

```
Request error: Get https://api.system.domain/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.


Errand 'deploy-service-broker' completed with error (exit code 1)

Exit code 1
```

Digging more into issue it seems to be issue with cf-cli which is being used inside SCS broker vms 

```
 /var/vcap/data/packages/cf-cli/a5a1fae984f4b0115a5948c496882b5a0ce4f885/bin/cf -v
cf version 6.32.0+0191c33d9.2017-09-26
```

When I manually install cf cli 6.4+ cf auth/login all works fine but version which is bundled there 
Is doing dns server timeout.

I see in /etc/resolve.conf 3 DNS server one from bosh default and other  2 from our platform which causing the issue I believe only with bosh DNS servers it works fine.

So how we can proceed from here. Please let us know how this DNS timeoout or cf-cli version bump up is feasible.

Best Regards
Ganesh Kumar

**Comment by kumarganesh2814** [comment]
```
deploy-service-broker/1240d336-c139-4fb9-b95a-2c393493518a:~# /var/vcap/data/packages/cf-cli/a5a1fae984f4b0115a5948c496882b5a0ce4f login -a api.us.system.oc.com
API endpoint: api.system.oc.com
FAILED
Error performing request: Get https://api.us.system.oc.com/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```

**Comment by csterwa** [comment]
@kumarganesh what version of PCF do you have installed?

**Comment by fifthposition** [comment]
Hi @kumarganesh2814! This repository is for Spring Cloud Services documentation, and we use it to track issues with the documentation (not the product itself). If you have a question or difficulty with installing or using Spring Cloud Services, please contact Pivotal Support.

**Comment by kumarganesh2814** [comment]
@fifthposition Sorry Ben. I also seen it later 
@csterwa Hey Chris 
We are on PAS/OpsMgr 2.2.8

Please let me know if I has to close case here or anyhow this can move to Install SCS github

Best Regards
Ganesh

**Comment by csterwa** [comment]
@kumarganesh2814 I'm going to close this issue since I think this should go through Pivotal Support. Please let me know if you have any questions about how to get support. Thanks.
