### ISSUE TITLE
Config Server Vault Backend - namespace parameter missing

### ISSUE THREAD

**Issue by kamalakarp** [pivotal-cf/docs-spring-cloud-services#324]
Team,

I have recently commited few changes to Spring Cloud Confiig Server which includes the namespace parameter which is needed for the enterprise version of Vault. namepsace parameter is already available with version 2.1.1 but it's still missing in Pivotal p-config-server accepting values.

My code changes : 
https://github.com/spring-cloud/spring-cloud-config/pull/1265 

        vault:
          port: 443
          scheme: https
          host: xxx
          backend: kv
          **namespace: devops/cicd**
          kv-version: 2

Current p-config-server parameters.
https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/configuring-with-vault.html

When i try to create a service broker by passing the namespace value, it's throwing the error.

cf create-service p-config-server standard devops-namespace-config-server-2 -c  "{\"vault\": { \"host\": \"xxx\", \"port\": \"443\", \"scheme\": \"https\", \"backend\": \"kv\", \"kvVersion\": \"2\", \"namespace\": \"devops\\cicd\" } }"
Creating service instance devops-namespace-config-server-2 in org DevOpsOrg / space VAULT as kamalakar ...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Service broker parameters are invalid: Error parsing Vault parameters:

If the Pivotal Spring Cloud Config Server doesn't have this as parameter, please let me know the github repo path and i can commit the necessary code changes.

Current accepted parameters.

Parameter | Function
-- | --
host | The host of the Vault server
port | The port of the Vault server
kvVersion | The Vault API version to use (values `1` or `2`). (default value: `1`)
scheme | The URI scheme used in accessing the Vault server. Default value: http
backend | The name of the Vault backend from which to retrieve configuration. Default value: secret
defaultKey | The default key from which to retrieve configuration. Default value: application
profileSeparator | The value used to separate profiles. Default value: ,
skipSslValidation | Whether to skip validation of the SSL certificate on the Vault server. Valid values: true, false

**Comment by csterwa** [comment]
Hello @kamalakarp, we noticed that you were using SCS `p-config-server` service. This service is the name from our SCS 2.0.x PCF tile and does not currently support the `namespace` or `kvVersion` parameters.

We recommend that you upgrade to SCS 3.0.x+ to get the new `p.config-server` service in your PCF marketplace. This does support those Vault parameters. We will add the `namespace` parameter` to the docs. Thank you for logging this issue since that was an oversight on our part.

**Comment by csterwa** [comment]
For this issue we should add the `namespace` property as a configurable option to support multi-tenant Vault environments. From the docs at https://www.vaultproject.io/docs/enterprise/namespaces/index.html, `namespace` is defined as: 

'Namespaces' is a set of features within Vault Enterprise that allows Vault environments to support Secure Multi-tenancy (or SMT) within a single Vault infrastructure. Through namespaces, Vault administrators can support tenant isolation for teams and individuals as well as empower delegated administrators to manage their own tenant environment.

**Comment by kamalakarp** [comment]
@csterwa if i start using SCS 3.0.x+to get the new p.config-server service in my PCF, will it supports namespace parameter ? it's not just documentation issue but p.config-server also need to take namespace parameter and pass it to the spring cloud config server. Is there a git repo to contribute the changes like i did for the Spring Cloud Config Server.

**Comment by csterwa** [comment]
@kamalakarp yes, we have verified it works on SCS 3.0+.

**Comment by kamalakarp** [comment]
Thank you @csterwa , I'll upgrade to SCS3.0+ to see if everything is working correctly or not
