### ISSUE TITLE
SecurityConfiguration

### ISSUE THREAD

**Issue by dambor** [pivotal-cf/docs-spring-cloud-services#325]
Apparently the @EnableWebSecurity annotation is missing from the SecurityConfiguration class example in the documentation. And the @profile should be cloud if you're suggesting to deploy it to PAS. Thanks

https://github.com/pivotal-cf/docs-spring-cloud-services/blob/v1.5/common/config-server/writing-client-applications.html.md.erb

https://docs.pivotal.io/spring-cloud-services/1-5/common/config-server/writing-client-applications.html#disable-http-basic-auth

**Comment by fifthposition** [comment]
Thanks @dambor! I think the profile was set to `development` because this configuration disables Spring Security, and the goal was to not enable this configuration except for development purposes. Will look into the missing `EnableWebSecurity`.
