### ISSUE TITLE
Document how best to store (especially nested) config properties in supported Config Server backends

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#329]
See SCS Slack thread on June 30, 2019.

(OLD DESC. BELOW)
When using Git, CredHub or HashiCorp, a Developer could use `@ConfigurationProperties` to handle nested properties efficiently. We should add documentation into writing client applications on how to use this annotation with all three backends. We may decide to put this into a separate area so we can discuss when this becomes prioritized.

**Comment by csterwa** [comment]
Only add this to `v3.x` and above.

**Comment by fifthposition** [comment]
Is this still something we'd like to add?

**Comment by csterwa** [comment]
@fifthposition yes, please. We should move this into priority. Thanks.

**Comment by habuma** [comment]
Is it really any different for each of the backends? Once a property/secret is served by config server, it's just another environment property that can be consumed in a number of ways, including `@ConfigurationProperties`, `@Value` or directly from the `Environment` abstraction. 

Moreover, while I tend to favor `@ConfigurationProperties`, I occasionally find reason to use other means, too. They are also valid options, so why focus on `@ConfigurationProperties`?

Finally, this is really a Spring Boot-level concern. Why not just reference Spring Boot documentation that describes how to use `@ConfigurationProperties`? (Especially if, as I believe, there's no difference across the various config server backends.)

**Comment by fifthposition** [comment]
After further discussion (see SCS Slack thread 3:15 Central US Feb. 14 2020), there seems to be almost nothing to do here. Added a link to the Vault CLI documentation in SCS 3.0 and 3.1 Config Server documentation.

3.0: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-vault.html#storing-configuration-properties
3.1: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuration-properties.html#vault
