### ISSUE TITLE
How to update Git properties via Config Server dashboard button

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#330]
Add documentation on the using the Update Git properties button on Config Server dashboard and link to mirror update documentation.

From #337 (merging with this issue)

See https://pivotal.slack.com/archives/C064Q28L9/p1564497058466100?thread_ts=1564494549.457500&cid=C064Q28L9 and the rest of the thread.

-----

Add new page "Refreshing Configuration Properties" to Config Server.

**Comment by csterwa** [comment]
This is for SCS 3.0.3 release.

**Comment by fifthposition** [comment]
Also document new CLI command `config-server-refresh`.

**Comment by csterwa** [comment]
@fifthposition is this in progress or blocked? I thought it was finished?

**Comment by fifthposition** [comment]
Oh I remember--I didn't remember completing this and I was wondering why I wouldn't have. I think I wasn't able to get a 3.0.3 or 3.1 build working on any of our environments so I went to the other project instead while I waited.

**Comment by csterwa** [comment]
Sorry @fifthposition - I couldn't tell from your comment whether this is finished or needs more work?

**Comment by fifthposition** [comment]
It isn’t done. At the time I started it I wasn’t able to get an environment that had a recent 3.0.3 installed and working.

**Comment by csterwa** [comment]
What is left to do @fifthposition ?

**Comment by fifthposition** [comment]
I’ve started this but won’t finish tonight and am out till next week—will try to get it in on Monday.

**Comment by fifthposition** [comment]
@csterwa I added #337 for a page that covers the different kinds of Config Server refresh--do you mind if I merge the two issues (that and this)?

**Comment by csterwa** [comment]
Please do.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html

**Comment by csterwa** [comment]
Looks good. Can you show the dashboard URL in the cf CLI too? Via cf service config-server command?

**Comment by fifthposition** [comment]
👍 Where should we show that?

**Comment by csterwa** [comment]
Maybe a separate section for using CLI?

**Comment by fifthposition** [comment]
Here's what we have for CLI: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html#refresh-mirrors-using-the-cf-cli

For the mention of the dashboard (at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html#refresh-mirrors-using-apps-manager -- different section), we do link to the "Using the Dashboard" page, which discusses using the cf CLI to find the dashboard.

Does that work?

**Comment by csterwa** [comment]
Can we change the section to Dashboard instead of Apps Manager? Then getting to dashboard can be described there?

**Comment by csterwa** [comment]
@fifthposition Please let me know if changing from `Apps Manager` to `Via Dashboard` so that the section is more focused on the dashboard button. And then we can reference how to get to the dashboard as you pointed out via:

https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/using-the-dashboard.html

**Comment by fifthposition** [comment]
@csterwa Done. How is this? https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html

**Comment by csterwa** [comment]
Great!
