### ISSUE TITLE
Add back Service Registry docs in v3.1

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#332]
We can bring back Service Registry docs from `v2.0` into `v3.1`.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/service-registry/index.html.

**Comment by csterwa** [comment]
@fifthposition looks great. I noticed that we need a story to change everything over to using `p.service-registry` in 3.1 rather than `p-service-registry`.
