### ISSUE TITLE
Update service plan name to `p.service-registry` in `v3.1` docs

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#333]
The name of the service plan is changing to `p.service-registry` in SCS `3.1.0`. We should update the docs to reflect this.

**Comment by fifthposition** [comment]
Updated mentions throughout. https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/service-registry/index.html

I removed a couple of sections or paragraphs which seem to no longer apply: in "Spring Cloud Connectors", we had removed the "Service Detection" section for Config Server and I removed it from Service Registry also; in "Using the Dashboard", we used to mention that you could find the dashboard URL from `cf service [SERVICE_NAME]`, but it no longer appears in that output so I removed that text.

**Comment by csterwa** [comment]
@fifthposition there is a story to add the dashboard URL back into the `cf service` output. Can you put that part back in before this is accepted?

**Comment by fifthposition** [comment]
I'll do that. I do think the output may be a little different from what it was, but for now I'll just put that back in.

**Comment by csterwa** [comment]
It should be the same except `/dashboard` may no longer be on the end. We have decided thus far to make the URL just the backing applications base URL. This works today and hasn't been added to the service output yet.

**Comment by fifthposition** [comment]
I'm not sure what to put then. This is what we had in our example output:

```
dashboard:       https://spring-cloud-broker.apps.example.com/dashboard/p.service-registry/ec0e615c-2a8c-40a9-9293-41b4a0db2a33
```

**Comment by csterwa** [comment]
Good point @fifthposition - we no longer send them through the service broker URL for accessing the dashboard. Can you put it back @fifthposition with that URL and then I'll update when we get to the story for adding the dashboard URL?

**Comment by fifthposition** [comment]
Done: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/service-registry/using-the-dashboard.html
