### ISSUE TITLE
Add blue/green deployment section with Service Registry suggested approach

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#335]
Here is documentation from our App Transformation team that they have found works well:

# Blue-Green Deploys When Using Eureka

A Blue-Green deploy is a method of deploying a new version of an application while the old version is still up and running. Smoke tests can be run on the new version to verify its functionality, then have traffic slowly move from the old version to the new, until the new version is taking all traffic for the application, making it safe to retire the old version.

When a service discovery service such as Eureka is in the mix, this gets more complicated, as the services/applications are registered under specific names for their clients, and being able to explicitly register under one name versus a name known to clients becomes a requirement.

This recipe details the steps required to deploy a service in a blue-green fashion while Eureka service discovery is in play.

## Important pieces of the service Registry

There are three main pieces that will need to change when deploying in a blue-green fashion when Eureka is in the mix:

* Application name
* Application Route
* Eureka registration name

Assume we start with an application configured as follows:

```
app name:  myapp
app route:  myapp.mydomain
eureka registry name:  myapp
```

When an application registers itself with Eureka, it uses the property spring.application.name, unless the property eureka.instance.appname exists and in that case that value is used instead. By setting the eureka.instance.appname property to be the value of an environment variable, we can modify this value with only an application restart. A sample application.properties appears as follows:

```
eureka:
  instance:
    appname: ${EUREKA_APP_NAME}
```

Package and push the application with this configuration and a manifest like this:

```
name: myapp-checkout
buildpack: java_buildpack_offline
path: target/myapp-1.0.0-SNAPSHOT.jar
memory: 1G
services:
    - service-registry
env:
  EUREKA_APP_NAME: myapp-checkout
host: myapp-checkout
```

this means we now have two applications: `myapp` and `myapp-checkout`. `myapp-checkout` is listening on the route `myapp-checkout.mydomain` and will register itself with eureka under the name `myapp-checkout` (due to the `EUREKA_APP_NAME` environment variable).

All smoke tests can be run on this app using the `myapp-checkout.mydomain` route, and the normal client traffic has not discovered this service as it has been registered with the name `myapp-checkout`.

To change the eureka registry name, simply set the environment variable and restart the app:

```
cf set-env myapp-checkout EUREKA_APP_NAME myapp
cf restart myapp-checkout
```

Now the app is listening under the route `myapp-checkout.mydomain` but has registered with Eureka under the name `myapp` (just as `myapp` has registered under the name `myapp`). This means that there are two apps registered with Eureka under the same name, and the side-by-side testing can begin.

During this phase, we can set the route of the `myapp-checkout` application to also include the route `myapp.mydomain`. Simply map a route as follows:

```
cf map-route myapp-checkout mydomain -n myapp
cf restart myapp-checkout
```

and now the `myapp-checkout` application has registred with Eureka under the name `myapp` and is also listening on the routes `myapp.mydomain` and `myapp-checkout.mydomain`

To remove the extra route, execute the following commands:

```
cf unmap-route myapp-checkout mydomain -n myapp-checkout
cf restart myapp-checkout
```

Now we have two applications registered with Eureka under the name `myapp` and listening on the route `myapp.mydomain`.

Once confidence in the new version of the app is satisfied, begin the cleanup of the old application by performing similar steps:

```
cf set-env myapp EUREKA_APP_NAME myapp-backout
cf unmap-route myapp mydomain -n myapp
cf map-route myapp mydomain -n myapp-backout
cf restart myapp
```

now the new version of the application (`myapp-checkout`) is listening on `myapp.mydomain` and registered with Eureka under the name `myapp`. The old version (`myapp`) is listening on `myapp-backout.mydomain` and registered with Eureka under the name `myapp-backout`.

To complete the transition, we rename the apps:

```
cf rename myapp myapp-backout
cf rename myapp-checkout myapp
```

and we return to the initial state, ready for the next deploy. Optionally, we can shut down `myapp-backout` as no traffic should be heading there directly:

```
cf stop myapp-backout
```

A complete solution would delete any `myapp-backout` application instances before starting this process. Automation for these steps is also important.

**Comment by csterwa** [comment]
This could go into the SCS 2.0.x docs, as well.

**Comment by fifthposition** [comment]
This sounds almost more like a guide external to the documentation, but I'm not aware of any place that we have customer-facing guides for the commercial Spring products. Does this still come up as an issue that people need to solve?

**Comment by csterwa** [comment]
No need to do this anymore.
