### ISSUE TITLE
Using private CA for generating PAS SSL certificates in v3.0

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#338]
In previous versions of SCS, there was a section on the home docs page describing the need to add two additional domains to the SSL certificate so that SCS could access platform services effectively. Since we remove that section, there was an issue for a customer where they were using a private CA to generate SSL certificates. That private CA's certificate needed to get put into the Java keystore of the BOSH VM that hosts the service broker and mirror service. The steps to resolve this were:

1. Add private CA cert to Bosh trusted certs (Ops Manager UI -> Director tile -> Security -> Trusted Certs) and save it.
2. Check the recreate all VMs flag to ensure that trust store on all the VMs will have private CA cert (Ops Manager UI -> Director tile -> Director Config -> Recreate All VMs)
3. Run the Apply changes on Bosh, PAS and SCS tile to ensure consistency across the founadation.

With these steps, any new SSL certificate that is rotated into the platform should be validated successfully when making SSL connections to platform services. We should add this into the Installation section of our Operator documentation.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/installation.html

**Comment by csterwa** [comment]
Let's push this to production @fifthposition

**Comment by fifthposition** [comment]
Done! https://docs.pivotal.io/spring-cloud-services/3-0/installation.html#using-a-private-ca
