### ISSUE TITLE
Add PAS CredHub being enabled as requirement for SCS 3.x+

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#340]
We had our first customer that asked if we could remove the dependency on PAS CredHub since the installation fails if it is not enabled today in SCS 3.x+. We cannot remove this dependency since PAS CredHub is used by our BOSH errands and service broker to create credentials for different aspect of the security model. We should add a bullet point in Requirements section that describes the explicit need to enable PAS CredHub to use SCS 3.x.

https://docs.pivotal.io/spring-cloud-services/3-0/common/index.html#requirements

**Comment by fifthposition** [comment]
This up at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/index.html

**Comment by csterwa** [comment]
Lets ship it! Great work.
