### ISSUE TITLE
Move 'Configuration Properties' info into 'Configuring with Git' and 'Configuring with Vault'

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#341]
On 'Configuration Properties', we have info about storing configuration in Git and Vault, but info for CredHub is in 'Managing Secrets with CredHub', which is more of a sister page to 'Configuring with Git' and 'Configuring with Vault'. Move the info about storing configuration to those pages and delete 'Configuration Properties'.

**Comment by csterwa** [comment]
@fifthposition the current CredHub implementation will only allow secrets to be placed in a single path location for an application. For example, an application `foo` will only receive secrets that are at path `/secrets/application/default/master` in CredHub by default. You can also pass in a profile name that replaces `default` in that path. And there is also the ability to replace label and change from default value of `master`.

**Comment by fifthposition** [comment]
This is up at:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html#storing-configuration-properties
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-vault.html#storing-configuration-properties
