### ISSUE TITLE
Upgrade service instances approach

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#344]
This page should include both:

* Upgrading an instance using `cf update-service myconfig -c '{"upgrade": true}'
* How to migrate from a `p-config-server` service instance to a `p.config-server` instance

This might go on the page at https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/managing-service-instances.html#updating.

**Comment by fifthposition** [comment]
New sections:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-service-instances.html#upgrading
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-service-instances.html#migrating-2-0-or-1-5-service-instances

**Comment by fifthposition** [comment]
@csterwa Forgot to ask if we also want this in 3.1. LMK if so and I'll cherry-pick.

**Comment by csterwa** [comment]
@fifthposition yes, this should go into all future minor versions.

**Comment by fifthposition** [comment]
Done.
