### ISSUE TITLE
Add section on how to use Git commit hash value from Config Server dashboard

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#345]
The Git commit hash for each configured repository on a Config Server service instance is now displayed on it's dashboard at the bottom. This commit hash is the currently mirrored version of the Git repository being served by the Config Server service instance. Given this information, a Developer could run a `git diff` for the `label` that is configured and the Git commit hash to see if there are any changes that have not been propagated to the Config Server.

**Comment by csterwa** [comment]
Please backport to 3.0.x docs, too.

**Comment by fifthposition** [comment]
3.1.x:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/using-the-dashboard.html

3.0.x:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/using-the-dashboard.html
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html#refresh-mirrors-using-the-dashboard (added note to say that the button is only available in 3.0.3 and later)
