### ISSUE TITLE
Recommend using service instance sharing across orgs/spaces when on same foundation

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#349]
Currently, in the peer replication section we describe how to use it for peering on same foundation across org/spaces.

https://docs.pivotal.io/spring-cloud-services/2-0/common/service-registry/enabling-peer-replication.html

We should change that sections to say if sharing service instances are turned on in foundation then we recommend using it instead of peer replication. The reason is that it will be more performant.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/service-registry/enabling-peer-replication.html.
