### ISSUE TITLE
Rebrand to Pivotal Spring Cloud Services for product name

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#350]
As part of our rebranding effort away from a suffix of `for PCF` towards prefixing with `Pivotal ...` on all products, we need to update our docs to reflect this change.

**Comment by fifthposition** [comment]
* 3.1: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/index.html
* 3.0: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/index.html
* 2.0: https://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/index.html
