### ISSUE TITLE
Add CLI commands for managing secrets on a Config Server instance

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#351]
We now have the following commands to manage secrets on a Config Server instance that are then stored in its PAS CredHub backend path:

```
$ cf config-server-add-credhub-secret
NAME:
   config-server-add-credhub-secret - Add secret in JSON format to the given path

USAGE:
      cf config-server-add-credhub-secret CONFIG_SERVER_INSTANCE_NAME CREDHUB_PATH JSON_SECRET

ALIAS:
   cs-add

$ cf config-server-remove-credhub-secret
NAME:
   config-server-remove-credhub-secret - Remove secrets from the given path

USAGE:
      cf config-server-remove-credhub-secret CONFIG_SERVER_INSTANCE_NAME CREDHUB_PATH

ALIAS:
   cs-remove
```

These should now be referenced as a preferred method for managing secrets on the page at:

https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html

**Comment by fifthposition** [comment]
This is up:

* 3.0: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html
* 3.1: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/managing-secrets-with-credhub.html
