### ISSUE TITLE
Update credhub secrets using the config server with Runtime CredHub

### ISSUE THREAD

**Issue by qaistars** [pivotal-cf/docs-spring-cloud-services#356]
I Know recently PCF Config Server added support for credhub but when every I try to add using /secrets endpoint getting this error :

```
"error": "Method Not Allowed",
"message": "Request method 'PUT' not supported",
``` 

I send http request with PUT to https://config-9d71fd1d-acb3-40ec-8ca6-d6fdaf9884f7.wipq.pcf.cvs.com/secrets/spring-credhub-demo/dev/jad

where :
app-name : spring-credhub-demo
spring-profile: dev
secret-name: jad

any suggestions?

**Comment by csterwa** [comment]
@qaistars Before answering your question, I wanted to make you aware that our docs now show how to use the SCS CF CLI plugin to manage secrets on a Config Server service instance:

https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html

As for using the API, I have a couple of questions:

* We you authenticated using the `cf` CLI to the PCF foundation?
* Did your command provide all of the command line args that are shown in docs as shown here:

`$ curl https://config-server-a5782192-8036-4f57-8312-4756a2604240.apps.example.com/secrets/cook/production/mylabel/secretmenu -H "Authorization: $(cf oauth-token)" -X PUT --data '{"secretMenu": "tacos"}' -H "Content-Type: application/json"`

**Comment by qaistars** [comment]
Yes I followed that document as is and provided all the required info for the request to be completed.

**Comment by csterwa** [comment]
@qaistars I noticed that the URL you provided was missing the label name, I think. Here is what I might expect when reformatting your URL:

https://config-9d71fd1d-acb3-40ec-8ca6-d6fdaf9884f7.wipq.pcf.cvs.com/secrets/spring-credhub-demo/dev/master/jad

Notice that I added `master` in this case.

**Comment by qaistars** [comment]
Yeah I tried with it as well still getting the same err

**Comment by csterwa** [comment]
@qaistars I just noticed that the URL you provided was from a SCS 2.x or prior version of the Config Server service. The new Config Server from SCS 3.0+ is now named `p.config-server`. In order for this to work you would need to migrate to the new SCS 3.0+ service. Sorry for the confusion.

**Comment by qaistars** [comment]
This is the only available for me unless there is away i can upgrade it

**Comment by fifthposition** [comment]
@qaistars For a Config Server from Spring Cloud Services 2.0.x, see the documentation at https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/index.html. CredHub support was added in Spring Cloud Services 3.0.x, so if your Config Server service instance is from Spring Cloud Services 2.0.x or earlier, it does not support the CredHub backend.

**Comment by qaistars** [comment]
@fifthposition @csterwa, thank you so much!

**Comment by kyleabu** [comment]
Hi, sorry we got the new version 3.0 but not I' getting 401 unauthorized err I believe the token gives me the read scope only and I'm not able to find the client-id and client-secret using cf env APP_NAME or cf service SERVICE_NAME so I read it from the env endpoint **vcap.services.speciality-base-config-server-3.1.credentials.client_secret** any suggestion?

**Comment by csterwa** [comment]
@kyleabu did you use the CF CLI plugin commands instead?

**Comment by kyleabu** [comment]
yes, using this command   `cf config-server-add-credhub-secret my-config-server cook/dev1/master/jad '{"jad": "value"}'`

getting error failed
