### ISSUE TITLE
Version 3.1 operator guide does not mention Service Registry

### ISSUE THREAD

**Issue by bthelen** [pivotal-cf/docs-spring-cloud-services#361]
In several sub-sections of the the `Operator Guide` section of the docs, there are mentions that the tile only supports the Config Server service, which is no longer true as of version 3.1.

**Comment by fifthposition** [comment]
Updated these pages:

* [Backup and Restore](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/backup-and-restore.html)
* [Tile Configuration](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/tile-configuration.html)
* [Service Instances](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/service-instances.html)
* [Client Dependencies](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/client-dependencies.html)

I could use special review of these sections:

* [Service Instances / Capacity Requirements](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/service-instances.html#capacity-requirements) (is the listing for Service Registry accurate?)
* [Client Dependencies / Service Registry](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/client-dependencies.html#service-registry) (is the list of what's included in the Service Registry starter still accurate?)

**Comment by csterwa** [comment]
Looks good @fifthposition and I believe these are accurate although I'm not sure we should list what is contained in it. No need to change though for now.
