### ISSUE TITLE
Add return status to `curl` output when managing secrets

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#367]
In the Adding a Secret and Removing a Secret sections we should provide a command that will output the HTTP response code. Using `curl` you can get the HTTP response code output by adding the `-i` flag.

Please verify the commands using `-i` flag and expected output.

**Comment by fifthposition** [comment]
This is up at:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/managing-secrets-with-credhub.html#adding-a-secret-using-endpoint
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/managing-secrets-with-credhub.html#removing-a-secret-using-endpoint
