### ISSUE TITLE
Create v2.1 navigation

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#373]
We are about the release Spring Cloud Services 2.1.0 and it will need a new site navigation in the docs such as we do for other minor versions. It should be a copy of `v2.0` docs with changes only to the version number, release dates and supports PCF 2.6+ components.

**Comment by fifthposition** [comment]
@csterwa Any change to SI versions? I am assuming no (assuming SI versions stay at `20` in 2.1).

**Comment by csterwa** [comment]
Yes, no change.

**Comment by csterwa** [comment]
@fifthposition I went to https://docs-pcf-staging.cfapps.io/spring-cloud-services/2-1/common/index.html and saw that the PCF versions were not updated in the `Product Snapshot` table. This should be OpsManager and PAS versions 2.6+. Also version and release date should be updated to `2.1.0` and October 31, 2019.

**Comment by csterwa** [comment]
Also @fifthposition, since we only support PCF 2.6+ then we should update the data services tile dependency versions to:

* RabbitMQ for PCF - 1.6+
* Pivotal MySQL - 2.5+

**Comment by fifthposition** [comment]
This is up (staging) at https://docs-pcf-staging.cfapps.io/spring-cloud-services/2-1/common/index.html

@csterwa Resolved those issues--sorry! Need to get back into having a release checklist for docs, I guess...

**Comment by csterwa** [comment]
Looks great!
