### ISSUE TITLE
Add `peer-timeout` configuration option for `p-service-registry` service instances

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#379]
The `peer-timeout` configuration for Service Registry service instances is being backported to SCS 2.x versions. We can pull the documentation for this configuration back into the `v2.0` and `v2.1` docs from:

https://docs.pivotal.io/spring-cloud-services/3-1/common/service-registry/enabling-peer-replication.html#configuration-parameters

**Comment by fifthposition** [comment]
See:

* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-1/common/service-registry/enabling-peer-replication.html#configuration-parameters
* http://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/common/service-registry/enabling-peer-replication.html#configuration-parameters
