### ISSUE TITLE
Add Actuator Endpoints page for Service Registry

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#384]
We currently have a page for Config Server and we should have either:

* A similar page as this one for Config Server https://docs.pivotal.io/spring-cloud-services/3-1/common/config-server/actuator-endpoints.html

* Or we can move the Actuator Endpoints up to the Developer Guide level and make it general for both services

**Comment by fifthposition** [comment]
I took the latter approach. https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/actuator-endpoints.html
