### ISSUE TITLE
Add `periodic` configuration option for Git repositories

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#385]
The following configuration will cause the Git repository's mirror to check and fetch changes from external Git server every 5 minutes:

`cf cs p.config-server standard myconfig -c '{"git": {"uri": "[REPO_URI]", "periodic": true}}'`

This can also be done in `composite` configurations:

`cf cs p.config-server standard myconfig -c '{"composite": [{"type": "git", "uri": "[REPO_URI]", "periodic": true}, {"type": "git", "uri": "[OTHER_REPO]"}]}'`

We should add this property and examples in both sections.

NOTE: This was added in version 3.1.2 patch release so this should also be noted.

**Comment by fifthposition** [comment]
This is at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuring-with-git.html#general-configuration. Added `periodic` to the first example of creating a composite backend Config Server SI at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/composite-backends.html#general-configuration

@csterwa There aren't any examples on the main "Configuring with Git" page, so I didn't add any. As I mentioned above, I added `periodic` to an example on the "Composite Backends" page, but there aren't many examples in these two pages. Let me know if what's here is sufficient.
