### ISSUE TITLE
Add section on System Logging configuration in tile configuration

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#388]
We don't currently have a section on how to configure syslog for SCS in our v3.0 & v3.1 docs:

https://docs.pivotal.io/spring-cloud-services/3-1/tile-configuration.html

We should add a `System Logging` section that explains configuration similar to what is on Pivotal MySQL tile docs:

https://docs.pivotal.io/p-mysql/2-7/install-config.html#syslog

**Comment by alek-sys** [comment]
What do you mean by "SCS inherits OM configuration when applicable"? I don't think there is a way to pick up syslog configuration from PAS. Or do you mean it should use the same settings as PAS?

**Comment by fifthposition** [comment]
New section is at https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/tile-configuration.html#syslog-configuration
