### ISSUE TITLE
Add refreshing mirrors to Developer Guide Config Server section

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#390]
Currently, the refreshing mirrors section is in the Operator Guide:

https://docs.pivotal.io/spring-cloud-services/3-1/common/config-server/mirror-service.html#refreshing-mirrors

This is probably something that should be a Developer Guide section. It could be added onto multiple pages: `Managing Service Instances` and `Configuring with Git`.

This should also include an explanation on using `periodic` parameter per Git repo configuration as an alternative to manual refreshing of mirrors.

**Comment by fifthposition** [comment]
It looks like we already added a page [Refreshing Configuration Properties](https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/refreshing-properties.html) in v3.0, but for whatever reason I didn't include that page in v3.1 (my guess is that I had already split off v3.1 by the time I added this page to v3.0), and this page was [added to v3.0](https://github.com/pivotal-cf/docs-spring-cloud-services/issues/330) before our 3.1.0 release.

I will bring that page into v3.1 and update it (in v3.0 too) to talk about `periodic`.

**Comment by fifthposition** [comment]
Correction: I didn't update the page in 3.0.x because `periodic` isn't in 3.0.x.

Here is the page in 3.1: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/refreshing-properties.html
