### ISSUE TITLE
Update client dependencies with 2.2.x & known issue with using 3.0.x+

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#394]
There is now a SCS Starters/Connectors 2.2.x library version to support Spring Cloud Hoxton release. We need to add this into the table at https://docs.pivotal.io/spring-cloud-services/3-1/common/client-dependencies.html#including-dependencies.

In addition, there is a known issue that client application developers must handle with Java buildpack when using SCS Starters 3.0.x+. We should add a note and section on how developers can successfully use SCS Starters 3.0.x currently.

**Comment by fifthposition** [comment]
@dyroberts Are you indeed taking this one or shall I attempt it?

**Comment by dyroberts** [comment]
@fifthposition If you're comfortable with it, I'd be happy to advise you on it.

**Comment by dyroberts** [comment]
@fifthposition There's more detail here https://docs.google.com/document/d/17U4OxkGbRsTQqYRziWrC7Xo7LG_6S_Ahmu-ah6BBHgQ

**Comment by fifthposition** [comment]
Thanks! I shall get to it then.

**Comment by fifthposition** [comment]
Updated table: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/client-dependencies.html#including-dependencies. See also the text following the table, and the build file examples (those have been switched to use SCS starters 2.2 instead of 3.1).

Added section about using 3.0 or later SCS starters: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/client-dependencies.html#using-starters-3-x-and-java-cfenv

**Comment by dyroberts** [comment]
@fifthposition Both look good!

**Comment by csterwa** [comment]
@fifthposition We should recommend using most recent 2.2.x release (I think 2.2.1.RELEASE as of this writing) and also put a note in that we recommend using 2.x versions as there are some incompatibilities with Java buildpack with 3.x versions.

**Comment by fifthposition** [comment]
@csterwa We currently (in what I linked to above) point out that you can’t use Spring Cloud Connectors in your app if you use the SCS starters v3.x, and we describe how you have to disable auto-reconfig on the JBP—do we want to say more than that and outright recommend against using v3?

**Comment by csterwa** [comment]
Yes, we want to recommend against using SCS Starters 3.x until the JBP is updated and we can mention the version it is resolved in.

**Comment by fifthposition** [comment]
Updated: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/client-dependencies.html#including-dependencies
