### ISSUE TITLE
Add note about removal of `encrypt.key` Config Server configuration from SCS 3.0.x & 3.1.x

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#397]
We should have a note on the Configuring with Git page for Config Server that mentions towards the top that `encrypt.key` is no longer supported.

**Comment by fifthposition** [comment]
3.1: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuring-with-git.html
3.0: https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html
