### ISSUE TITLE
Document encrypt.key setting for Config Server

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-services#403]
Added to SCS 3 in 3.1.6 and 3.0.12. See SCS 3 issue no. 1316.

**Comment by fifthposition** [comment]
3.1:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuring-with-git.html#encryption-and-encrypted-values
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuration-properties.html#encrypted-configuration

3.0:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html#encryption-and-encrypted-values
* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html#encrypted-configuration

**Comment by csterwa** [comment]
@fifthposition I just noticed that the examples don't incorporate a specific change we made. The `encrypt.key` property is now included in each Git repo object rather than separate for the entire Config Server. Here is an example:

```
$ cf update-service config-server -c '{"git": { "uri": "https://github.com/spring-cloud-services-samples/fortune-teller", "searchPaths": "configuration", "encrypt": { "key": "MYKEY" } } }'
```

Notice it is inside the `git` object rather than outside at top level.

**Comment by csterwa** [comment]
We should probably make a note of that change for users so that it is hard to miss.

**Comment by csterwa** [comment]
Also, I think we should always use `curl` commands with a HTTPS example URL in alignment with our documentation approaches for secure URL usage. The example could be modified to `https://SERVER/encrypt`.

**Comment by fifthposition** [comment]
@csterwa Updated example URLs to use HTTPS.

3.1:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-1/common/config-server/configuring-with-git.html#encryption-and-encrypted-values

3.0:

* https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/configuring-with-git.html#encryption-and-encrypted-values
