### ISSUE TITLE
images in create circuit breaker using apps manager is wrong

### ISSUE THREAD

**Issue by haodut** [pivotal-cf/docs-spring-cloud-services#53]
The images in create circuit breaker using apps manager is wrong, the images are services registry, not circuit breaker on https://docs.run.pivotal.io/spring-cloud-services/circuit-breaker/creating-an-instance.html
![54](https://cloud.githubusercontent.com/assets/1207669/24947529/c9f61c68-1f99-11e7-856f-84d2bf3f574b.png)

**Comment by animatedmax** [comment]
Thank you for pointing this out haodut -- we'll publish corrected images for these right away.
