### ISSUE TITLE
Composite Git Backend Exposes Passwords

### ISSUE THREAD

**Issue by stevenhartmann** [pivotal-cf/docs-spring-cloud-services#59]
I'm using PCF with Config Server service version 1.4.2 and the composite git backend approach exposes the git repo passwords instead of replacing them with stars like the individual git repo approach does (i.e., "****"). Is there some additional configuration that I need to pass to enable the password obfuscation feature?

For reference, this is the JSON that I am using (with actual values removed):

`cf update-service composite-config-server -c '{ "composite": [ { "git" : { "uri": "<uri1>", "username": "<username>", "password": "<password>"}}, { "git" : { "uri": "<uri2>", "username": "<username>", "password": "<password>"}} ] }'`

**Comment by scottfrederick** [comment]
@stevenhartmann This issue was fixed in SCS 1.4.3: http://docs.pivotal.io/spring-cloud-services/1-4/release-notes.html#1-4-3

**Comment by stevenhartmann** [comment]
Awesome! That's good to hear. And thanks for the quick response.
