### ISSUE TITLE
Missing information on Service registry client (SSL)

### ISSUE THREAD

**Issue by EvanCoh** [pivotal-cf/docs-spring-cloud-services#60]
Hello,

I am reading the specs you have on your website on this page:

https://docs.pivotal.io/spring-cloud-services/1-4/common/service-registry/writing-client-applications.html

and while reading "Add Self-Signed SSL Certificate to JVM Truststore" I could not figure out what is the url that I should use for TRUST_CERTS on Pivotal Web Services, or if I am to upload a self signed certificate (in that case, how/where?). 
If all of this is knowledge that is external to documentation of setting up a client to the eureka server can you please specify a link to some instructions?

Thank you,
Evan

**Comment by scottfrederick** [comment]
@EvanCoh These docs say `If your Pivotal Cloud Foundry (PCF) installation is using a self-signed SSL certificate, the certificate will need to be added to the JVM truststore...`. PWS doesn't use self-signed SSL certificates to sign HTTPS transactions, it uses a certificate from a well-known root certificate authority. None of the documentation that mentions self-signed certificates applies when using PWS.
