### ISSUE TITLE
configserver, vault description suggestions

### ISSUE THREAD

**Issue by mkrumpeio** [pivotal-cf/docs-spring-cloud-services#62]
In https://github.com/pivotal-cf/docs-spring-cloud-services/blob/v1.4/common/config-server/configuring-with-vault.html.md.erb
Found that the skipSslValidation flag should not be used if using vault port 8200, and not going through any http/s protocol or proxy. 
Once customer removed the flag, their cli command worked fine, otherwise it was throwing back a 502 error.
May be useful to simply note in the right column: Only use if host uri is http or https. If not, do not use.

**Comment by csterwa** [comment]
@mkrumpeio this is an interesting test case that we didn't see. I have a few questions regarding this scenario. Can you provide more specific information about the configuration that you used? Also, if not HTTP/HTTPS, which protocol did you need to configure? Or was it only the proxy configuration?

**Comment by csterwa** [comment]
@mkrumpeio please let us know if you have more specific information around this issue. I don't believe we understand the details enough to make the docs update suggested. Thank you.

**Comment by csterwa** [comment]
Closing issue for now. Please re-open and provide more specifics if this is still an issue. Thank you.
