### ISSUE TITLE
Config Server’s configuration dashboard w/o input fields on PCFDev 0.547.0

### ISSUE THREAD

**Issue by syr** [pivotal-cf/docs-spring-cloud-services#83]
Hello,

I'm on PCFDev 0.547.0 and added a config service via Apps Manager  (apps.local.pcfdev.iowhich) which succeeded, referring to `cf service config-server`.

However, setting the git URI for the config server via Config Server’s configuration dashboard
(https://spring-cloud-broker.local.pcfdev.io/dashboard/p-config-server/8a35214b-d1d2-4304-be94-c3e82a357cda) is not possible because there is only:
`Instance ID: 8a35214b-d1d2-4304-be94-c3e82a357cda`
`{
	"count": 1
}`

while I expected something like this:
https://docs.pivotal.io/spring-cloud-services/1-0/images/config-server/manage-config-server.png

Any ideas how to fix the dashboard?

**Comment by syr** [comment]
setting the property by cf sli also fails, although my command complies the usage example:

example: `cf update-service mydb -c '{"ram_gb":4}'`
mine: `cf update-service config-server -c '{ "git": { "uri": "https://github.com/spring-cloud-services-samples/cook-config", "label": "master" } }'`

**Comment by csterwa** [comment]
@syr we currently don't support configuring Config Server service instance's via Apps Manager or Config Server dashboard.

I would like to see more about what problems you are seeing when running those commands. Could you provide the following information:

* What OS you are running command on and terminal if that is relevant like on Windows?
* What `cf service config-server` says in it's output once it fails?
* Could you describe what `cf sli` is?
* What version of the `cf` CLI are you using?

**Comment by csterwa** [comment]
@syr based on the renaming of the issue, is this more of a feature request to have editing capabilities on the Config Server dashboard?

**Comment by syr** [comment]
Hi @csterwa,

I'm a bit confused about that missing feature as there is a screenshot of form incl. submit button which suggests that there is a possibility to configure the config server via dashboard: 
https://docs.pivotal.io/spring-cloud-services/1-0/images/config-server/manage-config-server.png

I'm on Win7 using default cmd.

On calling 
`cf create-service -c '{ "git": { "uri": "https://github.com/spring-cloud-services-samples/cook-config", "label": "master" } }' p-config-server standard config-server2`
I get:
`FAILED
Incorrect Usage. Requires service, service plan, service instance as arguments`

Creation of config server via app manager works and status is like:
cf service config-server

Showing info of service config-server in org pcfdev-org / space pcfdev-space as admin...
name:            config-server
service:         p-config-server
bound apps:
tags:
plan:            standard
description:     Config Server for Spring Cloud Applications
documentation:
dashboard:       https://spring-cloud-broker.local.pcfdev.io/dashboard/p-config-server/8a35214b-d1d2-4304-be94-c3e82a357cda

Showing status of last operation from service config-server...
status:    create succeeded
message:
started:   2018-01-26T14:02:08Z
updated:   2018-01-26T14:03:12Z
What do you mean by `cf sli`?

My CF CLI version is: `>cf -v
cf version 6.34.1+bbdf81482.2018-01-17`

Somehow code quoting is broken if there are empty lines, after removing them the big block became unreadable so I removed code block quotes.

**Comment by csterwa** [comment]
@syr the form you referenced is from the original version of Spring Cloud Services [v1.0] that is no longer supported. Sorry about the confusion in the docs. The most recent docs would be for v1.5. Here is a link to the most recent docs:

http://docs.pivotal.io/spring-cloud-services/1-5/common/

The `create-service` command does need some changes based on what I saw. The command has the service name and plan out of order. Here is an example that should work:

`cf create-service p-config-server standard config-server2 -c '{ "git": { "uri": "https://github.com/spring-cloud-services-samples/cook-config", "label": "master" } }'`

I believe the `-c` options must come after the service name and plan and the name of the service instance.

As for creating a Config Server service instance via Apps Manager, it will create a Config Server but it can't be configured with any Git repos to pull configuration properties from. Therefore we only support configuration of a Config Server via CF CLI using `-c` argument json.

**Comment by csterwa** [comment]
@syr did the command that I sent in the last comment work successfully or were there still issues?

**Comment by csterwa** [comment]
@syr I'm going to close this issue for now. Please feel free to reopen if there is further discussion needed. Thank you.

**Comment by amrit14rajsingh** [comment]
How to provide username and password for GITHUB repo, as far as spring cloud config service is concern.
cf create-service p-config-server standard spring-cloud-config-server1 -c '{ \"git\": { \"uri\": \"https://github.com/****/****.git\", \"label\": \"master\", \"username\": \"************@rediffmail.com\", \"password\": \"*****************\" } }'

**Comment by fifthposition** [comment]
@syr You cannot configure a Config Server service instance in Apps Manager (that UI). We recommend using the command line as documented at https://docs.pivotal.io/spring-cloud-services/1-5/common/config-server/managing-service-instances.html.
