### ISSUE TITLE
Broken Link in Troubleshooting Client Applications

### ISSUE THREAD

**Issue by Snesi** [pivotal-cf/docs-spring-cloud-services#89]
In this page of the documentation [https://github.com/pivotal-cf/docs-spring-cloud-services/blob/v1.5/common/client-troubleshooting.html.md.erb](https://github.com/pivotal-cf/docs-spring-cloud-services/blob/v1.5/common/client-troubleshooting.html.md.erb)

In the part where it says:

> If your PCF environment is using self-signed certificates, make sure that you have set the TRUST_CERTS environment variable on the application to the Elastic Runtime API endpoint as described in the Add Self-Signed SSL Certificate to JVM Truststore section of the Writing Client Applications topic in the Service Registry documentation.

The link to "Add Self-Signed SSL Certificate to JVM Truststore" is broken.

/spring-cloud-services/service-registry/writing-client-applications.html#self-signed-ssl-certificate

**Comment by csterwa** [comment]
Thank you @Snesi. It looks like the anchor is not available due to being a partial in the page. I'll update to be the main page link.

**Comment by csterwa** [comment]
PR: https://github.com/pivotal-cf/docs-spring-cloud-services/pull/90

**Comment by Snesi** [comment]
No that's not the problem. The problem is that the documentation doesn't exist. If you look for it on the page you'll see it's not there.

**Comment by Snesi** [comment]
Ok I found the documentation. This is what I think should appear:

https://github.com/pivotal-cf/docs-spring-cloud-services/blob/c3e8ad2d32ded64bc334e0d0a07132d442afa067/common/service-registry/_self-signed-ssl.html.md.erb

**Comment by csterwa** [comment]
@Snesi ah yes, I need to add the `/common` since it was moved awhile back and we missed this link. Thank you. I will fix this.
